
spring:
  application:
    name: todo
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG


# Environment Variable for Frontend URL
frontend-url: ${FRONTEND_URL}


#spring.application.name=todo
#spring.datasource.url=jdbc:mysql://localhost:3306/todo?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=Mukesh@999
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect


#spring.application.name=todo
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#spring.application.name=todo
#spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_tododb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=freedb_temptodo
#spring.datasource.password=f7UKKS&y8t3yzvE
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

